name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run pipeline
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        #   BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        #   AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   FILE_KEY: ${{ secrets.FILE_KEY }}
        run: |
          dvc repro


       # 🔵 Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 🐳 Build and push Docker image to ACR
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/flaskapp:latest .
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.AZURE_CONTAINER_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/flaskapp:latest
